name: CI / CD Pipeline (Terraform)
on:
 - push
 - workflow_dispatch

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13"
      
      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Create backend.hcl configuration file
        run: |
          cat << EOF > backend.hcl
          bucket         = "${{ vars.TF_BACKEND_BUCKET }}"
          key            = "${{ vars.TF_BACKEND_KEY }}"
          region         = "${{ vars.AWS_REGION }}"
          dynamodb_table = "${{ vars.TF_BACKEND_DYNAMO_TABLE }}"
          encrypt        = true
          EOF
      
      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl
      
      - name: Terraform Plan
        run: |
          terraform plan \
            -var region="${{ vars.AWS_REGION }}" \
            -var db_user="${{ secrets.DB_USER }}" \
            -var db_password="${{ secrets.DB_PASSWORD }}"

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.repository == 'Video2Frames/infrastructure'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install zip tool
        run: |
          set -e
          sudo apt update -y
          sudo apt install -y zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Create backend.hcl configuration file
        run: |
          cat << EOF > backend.hcl
          bucket         = "${{ vars.TF_BACKEND_BUCKET }}"
          key            = "${{ vars.TF_BACKEND_KEY }}"
          region         = "${{ vars.AWS_REGION }}"
          dynamodb_table = "${{ vars.TF_BACKEND_DYNAMO_TABLE }}"
          encrypt        = true
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var region="${{ vars.AWS_REGION }}" \
            -var db_user="${{ secrets.DB_USER }}" \
            -var db_password="${{ secrets.DB_PASSWORD }}"
